#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2022 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_repo_name_goes_here::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my $res = $http->get("https://api.github.com/repos/google/ngx_brotli/releases");
    if ( !$res->{success} ) {
        die "Could not GET ngx_brotli info from github ($res->{status} $res->{reason})\n\t Throttled? `curl -I https://api.github.com/rate_limit 2>&1 | grep ^X-RateLimit`\n";
    }

    # get $version, $url, $name from $res
    my $version = ea4_tool::util::json2ref( $res->{content} )->[0]{tag_name};
    $version =~ s/v//;

    my $suffix = "";
    if ( $version =~ s/rc$// ) {    # rc make things diffcult so lets drop it for this repo
        $suffix = "rc";
    }
    die "Could not determine version from github\n" if !$version;

    my $name = "$version.tar.gz";                                                        # needs to match $version
    my $url  = "https://github.com/google/ngx_brotli/archive/v$version$suffix.tar.gz";

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # github does not currently have a way to get the sum

    return;
}

__END__

=encoding utf-8

=head1 README

Typical github release-tag pattern
